logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 80
spring:
  profiles:
    active: mac
  batch:
    job:
      names: ${job.name:NONE}
  application:
    name: r104
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username: user01
    password: user01
