logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 80
spring:
  batch:
    job:
      names: ${job.name:NONE}
  application:
    name: r1012
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://192.168.100.100:3306/r102?serverTimezone=Asia/Seoul
    username: user01
    password: user01
