logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 80
spring:
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/r101?serverTimezone=Asia/Seoul
    username: user01
    password: user01
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 236688160662-e8dujfgqhk0973dhptcpecqp2gqu5qn9.apps.googleusercontent.com
            client-secret: vu75SyUk5_Hej8M1vcwQD31a
            scope: email
          naver:
            client-id: 3hQNIWLWUNpYslC7cW59
            client-secret: zREWMzyGES
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
